config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: "home#index"
  get 'signout', to: 'sessions#destroy', as: 'signout'
    resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :chats
  resources :messages


  root to: "home#index"
end

app/models/chat.rb
class Chat < ActiveRecord::Base
  has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :chat
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid, exists: true).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def self.user_name(user_id)
    User.find_by_id(user_id).name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :current_chat

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_chat
    @current_chat ||= Chat.first
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def create
    if chat = Chat.create
      redirect_to root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_chat
      @messages = current_chat.messages
    end
  end

  def show
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    if current_user
      if message = current_chat.messages.create(message_params)
        ActionCable.server.broadcast 'messages',
          message: message.message,
          username: User.user_name(message.sender_id),
          id: message.id
        head :ok  
      end
    else
      head :error
    end
  end

  private

  def message_params
    params[:sender_id] = current_user.id
    params.permit(:sender_id, :message)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env['omniauth.auth'])
    broadcast(user)
    session[:user_id] = user.id
    redirect_to root_path    
  end

  def destroy
    current_user.update_attributes(exists: false)
    broadcast(current_user)
    session[:user_id] = nil
    redirect_to root_path
  end

  def failure
    redirect_to request.env['omniauth.origin']
  end

  private 

  def broadcast(user)
    ActionCable.server.broadcast 'sessions',
          id: user.id,
          create: user.exists,
          name: user.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.slim
- if current_chat
  div class='chat'
    div class='participants'
        - User.where(exists: true).each do |user|
          p class='online-users' user-id='#{user.id}'
            = user.name
    div class='chat-window'
      div class='message-board'
        - if @messages
          - @messages.each do |message|
            div class='message' message-id='#{message.id}'
              div class='user-info'
                = User.user_name(message.sender_id)
              dev class='message-text'
                = message.message
      div class='input-area'
        textarea class='input' rows='3'
- else
  div class='new-chat'
    = link_to 'NewChat', chats_path, method: :post

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PublicChat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div>
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>

<%= yield %>

</body>
</html>